add update, delete methods to book controller, add liquibase support, add dev controller for fast fill db purposes
ihorromaniuk/bookstore pull request #3
Opened 2024-12-05 06:20 UTC by ihorromaniuk

2024-12-05 13:18 UTC, Elena-Bruyako requested changes
see comments

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/controller/BookController.java
> +        return ResponseEntity.noContent().build();
```suggestion
    public void deleteBook(@PathVariable Long id) {
        bookService.delete(id);
```

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/controller/BookController.java
> +    @DeleteMapping("/{id}")
```suggestion
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
```

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/controller/BookController.java
> +        return ResponseEntity.ok(bookService.update(id, requestDto));
```suggestion
    public BookDto updateBook(@PathVariable Long id,
                                        @RequestBody UpdateBookRequestDto requestDto) {
        return bookService.update(id, requestDto);
```

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/controller/DevController.java
> +public class DevController {
remove this controller

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/service/impl/BookServiceImpl.java
> +        if (bookRepository.existsById(id)) {
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(()....
        bookMapper.updateBookFromDto(requestDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/mapper/BookMapper.java
> +    Book updateDtoToModel(UpdateBookRequestDto dto);
```suggestion
    void updateBookFromDto(UpdateBookRequestDto dto, @MappingTarget Book entity);
```

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/service/impl/BookServiceImpl.java
> +        bookRepository.deleteById(id);
also, you can check if book exists

2024-12-05 13:18 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-column-is-deleted.yaml
> +                  name: is_deleted
add this column to existing changelog 01 and remove this changeset

2024-12-05 16:52 UTC, ihorromaniuk commented on src/main/java/core/basesyntax/bookstore/controller/DevController.java
> +public class DevController {
Why? I need it to speed up dev process

2024-12-06 11:32 UTC, Elena-Bruyako approved these changes

2024-12-06 12:09 UTC, merged