jpa-specification
ihorromaniuk/bookstore pull request #4
Opened 2024-12-05 08:49 UTC by ihorromaniuk

common practice to keep GET HTTP methods without body, so made POST instead

2024-12-05 13:33 UTC, Elena-Bruyako requested changes
see comments

2024-12-05 13:33 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/controller/BookController.java
> +    public ResponseEntity<?> getBooksBySpec(@RequestBody BookParamsDto params) {
```suggestion
    public List<BookDto> getBooksBySpec(BookParamsDto params) {
```

2024-12-05 13:33 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/controller/BookController.java
> +        return ResponseEntity.ok(bookService.findAll(params));
```suggestion
        return bookService.findAll(params);
```

2024-12-05 13:33 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/dto/book/BookParamsDto.java
> +public record BookParamsDto(String partTitle, String[] authors) {
```suggestion
public record BookParamsDto(String[] titles, String[] authors) {
```

2024-12-05 13:33 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/exception/BeanNotFoundException.java
> +public class BeanNotFoundException extends RuntimeException {
remove

2024-12-06 12:22 UTC, ihorromaniuk commented on src/main/java/core/basesyntax/bookstore/dto/book/BookParamsDto.java
> +public record BookParamsDto(String partTitle, String[] authors) {
discussed in chat

2024-12-06 12:22 UTC, ihorromaniuk commented on src/main/java/core/basesyntax/bookstore/exception/BeanNotFoundException.java
> +public class BeanNotFoundException extends RuntimeException {
discussed in chat

2024-12-06 12:35 UTC, Elena-Bruyako approved these changes

2024-12-06 12:57 UTC, merged