Global exception handler
ihorromaniuk/bookstore pull request #5
Opened 2024-12-06 13:56 UTC by ihorromaniuk

2024-12-07 09:34 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-12-07 09:34 UTC, Elena-Bruyako commented on pom.xml
> +			<artifactId>hibernate-validator</artifactId>
it's better to use `spring-boot-starter-validation`

2024-12-07 09:34 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/dto/book/CreateBookRequestDto.java
> +public record CreateBookRequestDto(@NotNull String title,
for String use `@NotBlank`

```suggestion
public record CreateBookRequestDto(@NotBlank String title,
```

2024-12-07 09:34 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/dto/book/UpdateBookRequestDto.java
> +public record UpdateBookRequestDto(@NotNull String title,
same here

2024-12-07 21:14 UTC, Elena-Bruyako requested changes
see comment

2024-12-07 21:14 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/bookstore/dto/book/CreateBookRequestDto.java
> +                                   @NotNull String isbn,
```suggestion
                                   @NotBlank String author,
                                   @NotBlank String isbn,
```

2024-12-09 08:41 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-12-09 15:36 UTC, merged